version: "3.7"
services:
  function-registry-db:
    image: postgres:9.4
    volumes:
      - pgdata:/var/lib/postgresql/data
    expose:
      - 5432
    environment:
      - POSTGRES_USER=hermes
      - POSTGRES_PASSWORD=hermes
    networks:
      - hermes
    restart: "on-failure"

  function-registry-api:
    image: hermeshub/function-registry-api:latest
    expose:
      - 8080
    networks:
      - hermes
    volumes:
      - ./logs/function-registry-api/:/app/logs
    restart: "on-failure"
    depends_on:
      - function-registry-db

  function-lifecycle-broker:
    image: redis
    expose:
      - 6379
    networks:
      - hermes
    restart: "always"

  function-orchestrator:
    image: hermeshub/function-orchestrator:latest
    environment:
      - DOCKER_BINARY_PATH=/usr/local/bin/docker
    ports:
      - ${PORT}:3000
    networks:
      - hermes
    volumes:
      - ./logs/function-orchestrator/:/app/logs
      - ./results:/app/results
      - /var/run/docker.sock:/var/run/docker.sock
    restart: "on-failure"
    depends_on:
      - function-lifecycle-broker
      - function-registry-api

volumes:
  pgdata:

networks:
  hermes:
    external: true
